name: devgate-audit-service
services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file:
      - '../../.env'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devgate-audit
      POSTGRES_DB: audit
    ports:
      - '5434:5432'
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
  app:
    image: amazoncorretto:21.0.9
    container_name: devgate-audit-service
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - "8082:8082"
    networks:
      - app_network
    volumes:
      - ../../build/libs:/app
      - ../../src/main/resources:/app/src/main/resources
    command: [ "java", "-jar", "/app/com.devgate.audit.audit-service.jar" ]
    depends_on:
      db:
        condition: service_healthy
networks:
  app_network:
    external: true

volumes:
  postgres_data: